//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.Seps.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SepsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SepsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acme.Seps.Text.SepsMessages", typeof(SepsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deactivate inactive {0}.
        /// </summary>
        internal static string CannotDeactivateInactiveEntity {
            get {
                return ResourceManager.GetString("CannotDeactivateInactiveEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be set.
        /// </summary>
        internal static string EntityNotSet {
            get {
                return ResourceManager.GetString("EntityNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be active.
        /// </summary>
        internal static string InactiveException {
            get {
                return ResourceManager.GetString("InactiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial values must not be changed.
        /// </summary>
        internal static string InitialValuesMustNotBeChanged {
            get {
                return ResourceManager.GetString("InitialValuesMustNotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} for period {1:d} - {2} with amount {3:C}.
        /// </summary>
        internal static string InsertParameter {
            get {
                return ResourceManager.GetString("InsertParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} for period {1:d} - {2} with amounts {3:C}/{4:C}.
        /// </summary>
        internal static string InsertTariff {
            get {
                return ResourceManager.GetString("InsertTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected {0} for period {1:d} - {2} with amount {3:C}.
        /// </summary>
        internal static string ParameterCorrection {
            get {
                return ResourceManager.GetString("ParameterCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful save of entities to database.
        /// </summary>
        internal static string SuccessfulSave {
            get {
                return ResourceManager.GetString("SuccessfulSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected {0} for period {1:d} - {2} with amounts {3:C}/{4:C}.
        /// </summary>
        internal static string TariffCorrection {
            get {
                return ResourceManager.GetString("TariffCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        internal static string ValueGreaterThanTheOther {
            get {
                return ResourceManager.GetString("ValueGreaterThanTheOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be zero or above.
        /// </summary>
        internal static string ValueZeroOrAbove {
            get {
                return ResourceManager.GetString("ValueZeroOrAbove", resourceCulture);
            }
        }
    }
}
